/**
 * First-class multi-page website packs for onboarding / template store.
 * Hand-authored recipes — not Motionsites near-clones.
 */
import type { TemplateCatalog } from '@platform/schemas'

export const WEBSITE_PACKS_CATALOG: TemplateCatalog = {
  version: 1,
  generatedAt: '2026-08-10T00:00:00.000Z',
  source: 'Platform website packs — multi-section landing recipes for common industries.',
  collections: [
    {
      id: 'landing',
      label: 'Landing pages',
      description: 'Whole-page starting points, hero through closing call to action.',
      count: 3,
    },
    {
      id: 'agency',
      label: 'Agency & portfolio',
      description: 'Studio and case-study work where the craft is the pitch.',
      count: 1,
    },
    {
      id: 'ecommerce',
      label: 'Ecommerce',
      description: 'Shop homes with product grids, carousels, and buy boxes.',
      count: 2,
    },
  ],
  templates: [
    {
      id: 'pack-local-trades',
      title: 'Local trades (plumber / installer)',
      collection: 'landing',
      category: 'website-pack',
      pageType: 'landing',
      style: ['modern', 'bold'],
      industry: ['local'],
      motionType: ['entrance', 'scroll-reveal'],
      complexity: 'moderate',
      mobileSafe: true,
      performanceClass: 'B',
      previewImage: '',
      previewVideo: '',
      islandReady: false,
      isFree: true,
      sourcePrompt:
        'Local trades landing: trust-first hero, services list, proof, contact details, simple footer. Practical and clear.',
      blockRecipe: [
        'hero-split-01',
        'services-list-01',
        'features-grid-01',
        'testimonials-grid-01',
        'contact-details-01',
        'cta-banner-01',
        'footer-simple-01',
      ],
    },
    {
      id: 'pack-agency-studio',
      title: 'Agency / studio',
      collection: 'agency',
      category: 'website-pack',
      pageType: 'landing',
      style: ['editorial', 'premium'],
      industry: ['agency', '*'],
      motionType: ['entrance', 'scroll-reveal'],
      complexity: 'moderate',
      mobileSafe: true,
      performanceClass: 'B',
      previewImage: '',
      previewVideo: '',
      islandReady: false,
      isFree: true,
      sourcePrompt:
        'Creative agency landing: bold hero statement, bento features, proof, CTA, contact, footer.',
      blockRecipe: [
        'hero-cover-statement-01',
        'features-bento-grid-01',
        'testimonials-grid-01',
        'cta-banner-01',
        'contact-details-01',
        'footer-simple-01',
      ],
    },
    {
      id: 'pack-restaurant',
      title: 'Restaurant / hospitality',
      collection: 'landing',
      category: 'website-pack',
      pageType: 'landing',
      style: ['editorial', 'premium'],
      industry: ['restaurant', 'local'],
      motionType: ['entrance', 'scroll-reveal'],
      complexity: 'simple',
      mobileSafe: true,
      performanceClass: 'A',
      previewImage: '',
      previewVideo: '',
      islandReady: false,
      isFree: true,
      sourcePrompt:
        'Restaurant site: appetite hero, menu-style features, reviews, reservation CTA, contact hours, footer.',
      blockRecipe: [
        'hero-centered-01',
        'features-grid-01',
        'testimonials-grid-01',
        'cta-banner-01',
        'contact-details-01',
        'footer-simple-01',
      ],
    },
    {
      id: 'pack-dtc-mealkit',
      title: 'DTC shop — meal kit / CPG',
      collection: 'ecommerce',
      category: 'website-pack',
      pageType: 'landing',
      style: ['modern', 'premium'],
      industry: ['ecommerce', 'restaurant'],
      motionType: ['entrance', 'scroll-reveal'],
      complexity: 'moderate',
      mobileSafe: true,
      performanceClass: 'B',
      previewImage: '',
      previewVideo: '',
      islandReady: false,
      isFree: true,
      sourcePrompt:
        'DTC meal-kit storefront: announcement, shop header, product buy box (plans + options), bestsellers grid, category tiles, CTA, footer.',
      blockRecipe: [
        'header-shop-announce-01',
        'header-simple-01',
        'product-detail-01',
        'product-card-grid-01',
        'product-category-tiles-01',
        'cta-banner-01',
        'footer-simple-01',
      ],
    },
    {
      id: 'pack-dtc-collectibles',
      title: 'DTC shop — comics / collectibles',
      collection: 'ecommerce',
      category: 'website-pack',
      pageType: 'landing',
      style: ['bold', 'editorial'],
      industry: ['ecommerce', 'creative'],
      motionType: ['entrance', 'scroll-reveal'],
      complexity: 'moderate',
      mobileSafe: true,
      performanceClass: 'B',
      previewImage: '',
      previewVideo: '',
      islandReady: false,
      isFree: true,
      sourcePrompt:
        'Independent comics storefront: loud announcement bar, product detail with variants, horizontal product carousel, CTA, footer.',
      blockRecipe: [
        'header-shop-announce-01',
        'header-simple-01',
        'product-detail-01',
        'product-carousel-01',
        'product-card-grid-01',
        'cta-high-contrast-01',
        'footer-simple-01',
      ],
    },
  ],
}
