/**
 * The storage seam (ADR-0006).
 *
 * Callers know that bytes go in under a key and come back out. They do not know
 * whether that is a directory on disk or a bucket in an object store, which is
 * the whole point: the driver is chosen at boot from configuration and can be
 * swapped without a single change above this file.
 */
export interface StorageProvider {
  /** Reported in health output and in tests, never branched on by callers. */
  readonly driver: 'local' | 's3'
  put(key: string, body: Buffer, contentType: string): Promise<void>
  /** `null` when the object is gone — a missing file is not an exception. */
  get(key: string): Promise<Buffer | null>
  remove(key: string): Promise<void>
}

/**
 * Keys are generated by this service, never by an uploader. The pattern below
 * is the enforcement of that: no leading slash, no `..`, no backslash, no
 * percent-encoding, no absolute path, no Windows drive letter.
 *
 * It is checked in *both* drivers rather than only at the call site, because a
 * guard that lives only at the call site is a guard the next call site forgets.
 */
const SAFE_KEY = /^[a-z0-9][a-z0-9/_-]*\.[a-z0-9]{1,8}$/

export class StorageKeyError extends Error {
  constructor(key: string) {
    super(`Unsafe storage key: ${JSON.stringify(key)}`)
    this.name = 'StorageKeyError'
  }
}

export function assertSafeKey(key: string): string {
  if (key.length > 400 || !SAFE_KEY.test(key) || key.includes('..') || key.includes('//')) {
    throw new StorageKeyError(key)
  }
  return key
}
