import "./ditto.css";
import ListRow from "./components/list-row";
import FeatureCard from "./components/feature-card";
import Tile from "./components/tile";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import Tile2 from "./components/tile2";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { kind: "link", href: "https://webtify.nl/klantverhalen/", label: "Klantverhalen" },
    { label: "Ontdekken" },
    { kind: "link", href: "#", label: "|" }
];
const FeatureCard_data = [
    { title: "Website", title2: "Business", description: "€250", description2: "€50", text: "12 ontwikkeluren", text2: "12 supporturen /jaar", text3: "Tot 15 pagina’s", text4: "Snelle hosting", href: "https://webtify.nl/abonnementen/website-business/" },
    { title: "Website", title2: "Business Plus", description: "€350", description2: "€150", text: "24 ontwikkeluren", text2: "24 supporturen /jaar", text3: "Meertaligheid", text4: "Cloud hosting", href: "https://webtify.nl/abonnementen/website-business-plus/" },
    { title: "Webshop", title2: "Business", description: "€350", description2: "€70", text: "12 ontwikkeluren", text2: "12 supporturen /jaar", text3: "Tot 50 producten", text4: "Snelle hosting", href: "https://webtify.nl/abonnementen/webshop-business/" },
    { title: "Webshop", title2: "Business Plus", description: "€450", description2: "€200", text: "24 ontwikkeluren", text2: "24 supporturen /jaar", text3: "Meertaligheid", text4: "Cloud hosting", href: "https://webtify.nl/abonnementen/webshop-business-plus/" }
];
const Tile_data = [
    { text: "Zelf doen", text2: "Lage kosten, maar veel tijd kwijt", text3: "Afhankelijk van je tijd en kennis", text4: "Je bent je eigen helpdesk", text5: "Alleen als je alles zelf kunt", text6: "Je moet weten wat je doet", text7: "AI-integraties mogelijk afhankelijk van CMS en kennis" },
    { text: "Freelancer", text2: "Vaak op uurtarief, dus ook vaak onduidelijk", text3: "Hangt af van beschikbare tijd", text4: "Vaak langzaam of even snel tussendoor", text5: "Alleen via freelancer in zijn/haar beschikbare tijd", text6: "Onvoorspelbaar", text7: "Soms AI-kennis aanwezig, vaak niet voldoende" },
    { text: "Webbureau", text2: "Hoge opstartkosten + factuur voor elke aanpassing", text3: "Lange trajecten. Vaak 6+ maanden.", text4: "Vaak alleen via het ticketssysteem", text5: "Vaak niet zelf te beheren, alles via het webbureau", text6: "Bij meerprijs vaak goed vindbaar in Google", text7: "Niet altijd AI-integraties en weinig zekerheid" }
];
const ListRow2_data = [
    { href: "https://webtify.nl/abonnementen/website-business/", label: "Website Business" },
    { href: "https://webtify.nl/abonnementen/website-business-plus/", label: "Website Business Plus" },
    { href: "https://webtify.nl/abonnementen/werkenbij/", label: "WerkenBij website" },
    { href: "https://webtify.nl/wordpress-ontwikkeling/", label: "Integraties" }
];
const ListRow2_data2 = [
    { href: "https://webtify.nl/abonnementen/webshop-business/", label: "Webshop Business" },
    { href: "https://webtify.nl/abonnementen/webshop-business-plus/", label: "Website Business Plus" },
    { href: "https://webtify.nl/woocommerce-functies/", label: "WooCommerce" },
    { href: "https://webtify.nl/betaalmogelijkheden-webshop/", label: "Betaalmogelijkheden" }
];
const ListRow2_data3 = [
    { href: "https://webtify.nl/ontdek-het-nieuwe-webtify/", label: "Het nieuwe Webtify" },
    { href: "https://webtify.nl/ons-verhaal/", label: "Ons verhaal" },
    { href: "https://webtify.nl/blog/", label: "Blog" },
    { href: "/affiliates", label: "Affiliates" },
    { href: "https://webtify.nl/klantverhalen/", label: "Klantverhalen" }
];
const ListRow3_data = [
    { ariadisabled: "true", text: " Functioneel " },
    { text: " Analytics " },
    { text: " Marketing & Sociale Media " }
];
const Tile2_data = [
    { label: " Weiger alles " },
    { kind: "button", label: " Accepteer selectie " },
    { kind: "button", label: " Accepteer alles " }
];
const ListRow_cids: string[][] = [
    ["n55", "n56"],
    ["n57", "n58"],
    ["n59", "n60"]
];
const FeatureCard_cids: string[][] = [
    ["n88", "n89", "n90", "n91", "n92", "n93", "n94", "n95", "n96", "n97", "n98", "n99", "n100", "n101", "n102", "n103", "n104", "n105", "n106", "n107", "n108", "n109", "n110", "n111", "n112", "n113"],
    ["n114", "n115", "n116", "n117", "n118", "n119", "n120", "n121", "n122", "n123", "n124", "n125", "n126", "n127", "n128", "n129", "n130", "n131", "n132", "n133", "n134", "n135", "n136", "n137", "n138", "n139"],
    ["n140", "n141", "n142", "n143", "n144", "n145", "n146", "n147", "n148", "n149", "n150", "n151", "n152", "n153", "n154", "n155", "n156", "n157", "n158", "n159", "n160", "n161", "n162", "n163", "n164", "n165"],
    ["n166", "n167", "n168", "n169", "n170", "n171", "n172", "n173", "n174", "n175", "n176", "n177", "n178", "n179", "n180", "n181", "n182", "n183", "n184", "n185", "n186", "n187", "n188", "n189", "n190", "n191"]
];
const Tile_cids: string[][] = [
    ["n224", "n225", "n226", "n227", "n228", "n229", "n230", "n231"],
    ["n232", "n233", "n234", "n235", "n236", "n237", "n238", "n239"],
    ["n240", "n241", "n242", "n243", "n244", "n245", "n246", "n247"]
];
const ListRow2_cids: string[][] = [
    ["n280", "n281"],
    ["n282", "n283"],
    ["n284", "n285"],
    ["n286", "n287"]
];
const ListRow2_cids2: string[][] = [
    ["n293", "n294"],
    ["n295", "n296"],
    ["n297", "n298"],
    ["n299", "n300"]
];
const ListRow2_cids3: string[][] = [
    ["n306", "n307"],
    ["n308", "n309"],
    ["n310", "n311"],
    ["n312", "n313"],
    ["n314", "n315"]
];
const ListRow3_cids: string[][] = [
    ["n456", "n457", "n458", "n459"],
    ["n460", "n461", "n462", "n463"],
    ["n464", "n465", "n466", "n467"]
];
const Tile2_cids: string[][] = [
    ["n469"],
    ["n470"],
    ["n471"]
];
const ListRow_styles = [
    { className: "h-5.5", className2: "cursor-pointer" },
    { className2: "pr-5 after:content-['3'] after:block after:absolute after:top-0 after:right-0 after:bottom-2 after:left-[5.0625rem] after:w-4 after:h-3.5 after:text-foreground after:text-base after:font-extrabold after:leading-3.5 after:text-right max-lg:after:bottom-auto max-lg:after:left-auto max-lg:after:w-auto max-lg:after:h-auto" },
    { className: "pointer-events-none", className2: "cursor-pointer pointer-events-none" }
];
const FeatureCard_styles = [
    { className: "mr-[34.5px] max-lg:mb-7.5 max-md:mr-0 md:max-lg:mr-[2.1125rem] 2xl:mr-10.5" },
    { className: "mr-[34.5px] max-lg:mb-7.5 max-lg:mr-0 2xl:mr-10.5", className2: "h-13" },
    { className: "mr-[34.5px] max-md:mb-7.5 max-md:mr-0 md:max-lg:mr-[2.1125rem] 2xl:mr-10.5" },
    { className2: "h-13" }
];
const ListRow2_styles = [
    { className: "h-6.5" },
    { className: "h-6.5" },
    { className: "h-6.5" },
    {  }
];
const ListRow2_styles2 = [
    { className: "h-6.5" },
    { className: "h-6.5" },
    {  },
    { className: "h-6.5" }
];
const ListRow2_styles3 = [
    { className: "h-6.5" },
    {  },
    {  },
    {  },
    { className: "h-6.5" }
];
const ListRow3_styles = [
    { className2: "cursor-not-allowed", className3: "border-border bg-background before:bg-border after:bg-border" },
    { className2: "cursor-pointer", className3: "border-foreground bg-foreground before:bg-background after:bg-foreground" },
    { className: "h-6", className2: "h-6 cursor-pointer", className3: "border-foreground bg-foreground before:bg-background after:bg-foreground" }
];
const Tile2_styles = [
    { className: "border-2 border-solid border-border hidden min-w-0 text-foreground bg-background" },
    { className: "border-2 border-solid border-border block text-foreground bg-background" },
    { className: "h-15 block text-background bg-foreground shadow-[var(--background)_0px_0px_0px_6px] max-md:h-auto" }
];

export default function Page() {
  return (
    <>
      <div className="block" data-cid="n1" id="page-container">
        <div className="block" data-cid="n2" id="et-boc">
          <header className="block max-lg:h-36.5 after:content-[''] after:block after:w-full after:h-0" data-cid="n3">
            <div className="block relative z-2" data-cid="n4">
              <div className="block relative z-1000 bg-foreground bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n5" id="header-topbar">
                <div className="w-288 h-10 flex relative max-w-350 mx-16 py-[0.3125rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-lg:block max-lg:max-w-[90%] max-md:mx-[1.175rem] md:max-lg:w-[43.2rem] md:max-lg:mx-[2.4rem] 2xl:w-350 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n6">
                  <div className="w-[544.3px] h-[1.7rem] min-h-px block relative float-left z-2 my-[0.0875rem] mr-[3.9625rem] order-[1] bg-cover [background-position:50%_50%] bg-no-repeat max-lg:hidden 2xl:w-[661.5px] 2xl:mr-[4.8125rem]" data-cid="n7">
                    <div className="block relative text-background text-[0.875rem] text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n8">
                      <div className="h-[1.7rem] block relative" data-cid="n9">
                        <a className="inline cursor-pointer" data-cid="n10" data-component="link" href="https://webtify.nl/webtify-in-de-emerce-100/">
                          🏆 Webtify staat in de EMERCE 100 2026!
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[544.3px] h-7.5 min-h-px block relative float-left z-2 order-[1] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-lg:flex max-lg:justify-center max-lg:items-center max-lg:order-[initial] md:max-lg:w-[43.2rem] 2xl:w-[661.5px]" data-cid="n11">
                    <div className="w-full block relative text-background text-[0.875rem] text-right [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat max-lg:h-7.5 max-lg:text-left" data-cid="n12">
                      <div className="block relative" data-cid="n13">
                        <ul className="h-7.5 block leading-6.5 [list-style-type:none] list-outside" data-cid="n14">
                          <li className="inline mr-5 max-lg:hidden" data-cid="n15">
                            <a className="inline cursor-pointer" data-cid="n16" data-component="link" href="/abonnementen" target="_blank">
                              {"Abonnementen & prijzen"}
                            </a>
                          </li>
                          <li className="inline mr-5 max-lg:hidden" data-cid="n17">
                            <a className="inline cursor-pointer" data-cid="n18" data-component="link" href="https://webtify.nl/vacatures/">
                              {"Vacatures "}
                              <span className="inline-block rounded-[20px] text-xs leading-[1.0625rem] text-center bg-primary" data-cid="n19" data-component="badge">
                                5
                              </span>
                            </a>
                          </li>
                          <li className="inline mr-5 max-lg:mr-0" data-cid="n20">
                            <div className="inline-block relative" data-cid="n21">
                              {" "}
                              <a className="inline cursor-pointer" data-cid="n22" data-component="link" href="https://webtify.nl/support/">
                                <span className="inline relative mr-2.5" data-cid="n23">
                                  <picture className="inline" data-cid="n24">
                                    {" "}
                                    <source className="inline" data-cid="n25" srcSet="/assets/cloned/images/b546e1e6c86a.webp" type="image/webp" />
                                    {" "}
                                    <img className="w-7.5 h-7.5 border-2 border-solid border-foreground inline max-w-full rounded-[100px] overflow-clip align-middle" data-cid="n26" data-component="avatar" src="/assets/cloned/images/0ea9937fe58d.jpg" />
                                    {" "}
                                  </picture>
                                  {" "}
                                  <picture className="inline -ml-2.5" data-cid="n27">
                                    {" "}
                                    <source className="inline" data-cid="n28" srcSet="/assets/cloned/images/4a559aaabae8.webp" type="image/webp" />
                                    {" "}
                                    <img className="w-7.5 h-7.5 border-2 border-solid border-foreground inline max-w-full rounded-[100px] overflow-clip align-middle" data-cid="n29" data-component="avatar" src="/assets/cloned/images/16e001b29f70.jpg" />
                                    {" "}
                                  </picture>
                                  {" "}
                                  <picture className="inline -ml-2.5" data-cid="n30">
                                    {" "}
                                    <source className="inline" data-cid="n31" srcSet="/assets/cloned/images/b57364f591c5.webp" type="image/webp" />
                                    {" "}
                                    <img className="w-7.5 h-7.5 border-2 border-solid border-foreground inline max-w-full rounded-[100px] overflow-clip align-middle" data-cid="n32" data-component="avatar" src="/assets/cloned/images/94e6797a6e6c.jpg" />
                                    {" "}
                                  </picture>
                                  {" "}
                                  <span className="w-3 h-3 border border-solid border-foreground block absolute -right-0.5 rounded-[10px] bg-color-006 after:content-[''] after:block after:absolute after:inset-0 after:w-2.5 after:h-2.5 after:shadow-[var(--clr-2)_0px_0px_0px_9.13404px] after:rounded-tl-[10px] max-md:after:shadow-[var(--clr-11)_0px_0px_0px_9.73328px] md:max-lg:after:shadow-[var(--clr-12)_0px_0px_0px_7.32297px] 2xl:after:shadow-[var(--clr-0)_0px_0px_0px_8.22071px]" data-cid="n33" />
                                </span>
                                {" Support"}
                              </a>
                            </div>
                            {" "}
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="block relative z-500 bg-background bg-cover [background-position:50%_50%] bg-no-repeat max-lg:mb-[0.9375rem]" data-cid="n34" id="header-mainmenu">
                <div className="w-288 h-[99.1px] min-h-12.5 flex relative z-3 max-w-350 mx-16 py-[1.5625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[23.4375rem] max-lg:h-[5.6875rem] max-lg:block max-lg:max-w-full max-lg:mx-0 md:max-lg:w-192 2xl:w-350 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n35">
                  <div className="w-[240.5px] h-[49.1px] min-h-px block relative float-left z-5000 order-[1] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[23.4375rem] max-lg:h-auto max-lg:order-[initial] md:max-lg:w-192 2xl:w-[292.3px]" data-cid="n36">
                    <div className="w-[10.9375rem] block relative inset-0 z-5000 bg-cover [background-position:50%_50%] bg-no-repeat cursor-pointer max-lg:h-[49.1px] max-lg:absolute max-md:left-[1.175rem] max-lg:right-auto max-lg:bottom-auto md:max-lg:left-[2.4rem]" data-cid="n37">
                      <div className="block relative" data-cid="n38">
                        <a className="inline text-primary" data-cid="n39" data-component="link" href="/">
                          {" "}
                          <svg className="w-auto h-[3.0625rem] block max-w-[10.9375rem] overflow-hidden" data-cid="n40" data-component="image" id="webtify-logo-header" viewBox="0 0 796.67 223.73" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                            <defs>
                              <style>
                                {".cls-1{fill:#023248}"}
                              </style>
                            </defs>
                            <path data-letter="W" className="cls-1" d="M195.96,0c-5.58,0-10.55,3.49-12.46,8.72l-46.93,128.78-28.62-80.16c-2.54-6.98-9.17-11.63-16.6-11.63s-15.23,4.36-17.81,11.27l-29.53,81.04-18.39-51.26c-1.84-5.15-6.72-8.58-12.18-8.58-9.01,0-15.79,9.51-12.67,17.95l27.71,76.38h29.49l32.13-84.47,30.88,84.47h30.36L208.4,17.86c3.19-8.66-3.21-17.86-12.44-17.86Z" />
                            <path data-letter="e" className="cls-1" d="M256.49,45.72c-37.62,0-65.31,26.97-65.31,64.6s27.45,64.83,69.8,64.83c21.77,0,39.51-7.1,50.87-20.59l-15.85-18.22c-8.99,9.23-20.11,13.73-34.31,13.73-22,0-37.38-11.83-40.93-30.29h99.14c.24-2.84.47-6.39.47-8.76,0-39.51-26.97-65.3-63.88-65.3ZM220.53,100.14c2.84-18.46,16.8-30.76,35.97-30.76s33.36,12.54,35.73,30.76h-71.69Z" />
                            <path data-letter="b" className="cls-1" d="M402.41,45.72c-16.09,0-30.29,5.44-40.46,16.8V14.79c0-8.17-6.62-14.79-14.79-14.79h0c-8.17,0-14.79,6.62-14.79,14.79v158.7h28.16v-16.33c9.94,12.07,24.61,17.98,41.88,17.98,36.91,0,64.12-25.55,64.12-64.83s-27.21-64.6-64.12-64.6ZM399.1,149.83c-21.3,0-37.62-15.38-37.62-39.51s16.32-39.52,37.62-39.52,37.38,15.38,37.38,39.52-16.09,39.51-37.38,39.51Z" />
                            <path data-letter="t" className="cls-1" d="M535.59,149.59c-12.31,0-17.75-6.86-17.75-20.35v-57.5h31.38v-23.66h-31.38V14.79c0-8.17-6.62-14.79-14.79-14.79s-14.79,6.62-14.79,14.79v33.3h-21.73v23.66h21.73v57.97c0,26.5,15.85,43.77,45.19,43.77h15.84l-.14-24.04-13.57.15Z" />
                            <circle data-letter="i" className="cls-1" cx="576.41" cy="14.9" r="14.79" />
                            <rect data-letter="i" className="cls-1" x="561.29" y="47.14" width="29.58" height="126.35" />
                            <path data-letter="fy" className="cls-1" d="M768.27,48.17l-37.49,86.49-37.49-86.49h-41.27v-3.92c0-13.49,6.39-20.35,18.69-20.35l12.71.15c6.7.08,12.16-5.33,12.16-12.02s-5.38-12.02-12.02-12.02h-14.98c-29.34,0-45.19,17.27-45.19,43.77v4.4h-20.46v23.58h20.46v101.74h29.58v-101.74h22.2l41.54,95.4-24.53,56.59h28.02l76.48-175.56h-28.4Z" />
                            <path data-letter="." className="cls-1" d="M781.45,149.83c-8.41,0-15.22,6.82-15.22,15.22s6.82,15.22,15.22,15.22,15.22-6.81,15.22-15.22-6.82-15.22-15.22-15.22Z" />
                          </svg>
                          {" "}
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[911.5px] h-9 min-h-px block relative float-left z-2000 my-[0.4125rem] grow order-[1] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[23.4375rem] max-lg:h-10 max-lg:my-0 max-lg:grow-[initial] max-lg:order-[initial] md:max-lg:w-192 2xl:w-[69.2375rem]" data-cid="n41">
                    <div className="block relative z-2000 text-right bg-clr-4 bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n42">
                      <div className="h-9 flex relative items-stretch max-lg:h-10 max-md:px-[1.175rem] max-lg:items-center md:max-lg:px-[2.4rem] after:content-['_'] after:block after:w-0 after:h-0 after:text-foreground after:text-[0rem] after:font-light after:leading-[1.6875rem] after:text-right" data-cid="n43">
                        <div className="h-9 flex flex-wrap justify-end items-stretch grow max-lg:h-10" data-cid="n44">
                          <div className="h-9 flex justify-start items-stretch max-lg:hidden" data-cid="n45">
                            <nav className="h-9 flex items-stretch" data-cid="n46" data-component="nav">
                              <ul className="h-9 flex -mx-[0.6875rem] flex-wrap justify-end items-center gap-x-2.5 [list-style-type:disc] list-outside" data-cid="n47" id="menu-hoofdmenu">
                                <li className="flex relative mt-2 px-[0.6875rem] items-center text-sm leading-3.5" data-cid="n48">
                                  <a className="block relative pr-5 pb-2 [overflow-wrap:break-word] cursor-pointer after:content-['3'] after:block after:absolute after:top-0 after:right-0 after:bottom-2 after:left-[4.1875rem] after:w-4 after:h-3.5 after:text-foreground after:text-base after:font-extrabold after:leading-3.5 after:text-right max-lg:after:bottom-auto max-lg:after:left-auto max-lg:after:w-auto max-lg:after:h-auto" data-cid="n49" data-component="link" href="https://webtify.nl/website-abonnement/">
                                    Websites
                                  </a>
                                </li>
                                <li className="flex relative mt-2 px-[0.6875rem] items-center text-sm leading-3.5" data-cid="n50">
                                  <a className="block relative pr-5 pb-2 [overflow-wrap:break-word] cursor-pointer after:content-['3'] after:block after:absolute after:top-0 after:right-0 after:bottom-2 after:left-19 after:w-4 after:h-3.5 after:text-foreground after:text-base after:font-extrabold after:leading-3.5 after:text-right max-lg:after:bottom-auto max-lg:after:left-auto max-lg:after:w-auto max-lg:after:h-auto" data-cid="n51" data-component="link" href="https://webtify.nl/webshop-abonnement/">
                                    Webshops
                                  </a>
                                </li>
                                <li className="flex relative mt-2 px-[0.6875rem] items-center text-sm leading-3.5" data-cid="n52">
                                  <a className="h-[1.5625rem] block relative pr-5 pb-2 [overflow-wrap:break-word] cursor-pointer after:content-['3'] after:block after:absolute after:top-0 after:right-0 after:bottom-[0.6875rem] after:left-21 after:w-4 after:h-3.5 after:text-foreground after:text-base after:font-extrabold after:leading-3.5 after:text-right max-lg:after:bottom-auto max-lg:after:left-auto max-lg:after:w-auto max-lg:after:h-auto" data-cid="n53" data-component="link" href="/ai-agent">
                                    {"AI Agent "}
                                    <img className="w-[0.9375rem] h-[0.9375rem] inline max-w-full overflow-clip aspect-[auto_15/15]" data-cid="n54" data-component="image" alt="" height="15" src="/assets/cloned/svg/6a4c1a145882.svg" width="15" />
                                  </a>
                                </li>
                                {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
                                <li className="w-[2.9375rem] flex relative px-[0.6875rem] items-center text-sm leading-3.5" data-cid="n61">
                                  <span className="block" data-cid="n62">
                                    <div className="inline-block relative" data-cid="n63">
                                      <div className="inline-block relative align-middle cursor-pointer" data-cid="n64">
                                        {" "}
                                        <img className="w-full h-[1.5625rem] inline max-w-full rounded-[25px] overflow-clip object-cover aspect-[auto_25/25]" data-cid="n65" data-component="avatar" alt="" height="25" src="/assets/cloned/svg/a69fdbbcf495.svg" width="25" />
                                      </div>
                                    </div>
                                    {" "}
                                  </span>
                                </li>
                                <li className="w-[10.3125rem] flex relative px-[0.6875rem] items-center text-sm leading-3.5" data-cid="n66">
                                  <a className="border border-solid border-accent block relative py-2.5 px-5 rounded-[5px] font-medium text-center [overflow-wrap:break-word] bg-accent cursor-pointer" data-cid="n67" data-component="link" href="https://webtify.nl/kennismaken/">
                                    Kennismaken
                                  </a>
                                </li>
                              </ul>
                            </nav>
                          </div>
                          <div className="hidden float-right min-w-0 max-lg:flex max-lg:mx-1.5 max-lg:items-center max-lg:[float:initial]" data-cid="n68">
                            <div className="block" data-cid="n69">
                              <span className="block relative leading-0 transform-[none] max-lg:transform-[matrix(1,0,0,1,0,1.2)]" data-cid="n70" />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </header>
          <div className="block" data-cid="n71" id="et-main-area">
            <div className="block" data-cid="n72" id="main-content">
              <article className="block" data-cid="n73" id="post-734">
                <div className="block" data-cid="n74">
                  <div className="block" data-cid="n75">
                    <div className="block relative z-1" data-cid="n76">
                      <div className="block relative py-[3.2rem] bg-background bg-cover [background-position:50%_50%] max-lg:py-12.5 2xl:py-13.5" data-cid="n77">
                        <div className="w-288 h-[7.325rem] block relative max-w-315 mx-16 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:h-[11.525rem] max-md:max-w-[90%] max-md:mx-[1.175rem] md:max-lg:w-[38.4rem] md:max-lg:max-w-270 md:max-lg:mx-[4.8rem] 2xl:w-315 2xl:mx-82.5 after:content-[''] after:block after:w-0 after:h-0" data-cid="n78">
                          <div className="w-full h-[7.325rem] min-h-px block relative float-left z-2 bg-cover [background-position:50%_50%] bg-no-repeat max-md:h-[11.525rem]" data-cid="n79">
                            <div className="h-full block relative max-w-350 text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n80">
                              <div className="h-full block relative" data-cid="n81">
                                <h2 className="h-22.5 block pb-2.5 text-4xl font-bold leading-10 max-md:h-32.5" data-cid="n82" data-component="heading">
                                  {"Kies het "}
                                  <span className="inline text-primary" data-cid="n83">
                                    {"abonnement "}
                                  </span>
                                  <br className="inline max-lg:hidden" data-cid="n84" />
                                  dat bij jou past!
                                </h2>
                                <p className="block" data-cid="n85">
                                  Geweldige websites. Snelle service. Eerlijke prijzen. Daar staan we voor.
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="block relative pb-[3.2rem] bg-background bg-cover [background-position:50%_50%] max-lg:pb-12.5 2xl:pb-13.5" data-cid="n86">
                        <div className="w-288 h-[22.5375rem] block relative max-w-350 mx-16 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:h-[1532.3px] max-lg:flex max-md:max-w-[90%] max-md:mx-[1.175rem] max-lg:flex-wrap md:max-lg:w-[38.4rem] md:max-lg:h-[46.95rem] md:max-lg:max-w-270 md:max-lg:mx-[4.8rem] 2xl:w-350 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n87">
                          {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} cids={FeatureCard_cids[i]} styles={FeatureCard_styles[i]} />)}
                        </div>
                      </div>
                      <div className="w-288 h-[50.8375rem] block relative max-w-350 my-12.5 mx-16 py-[3.2rem] rounded-[25px] overflow-hidden bg-color-003 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:h-230.5 max-md:mx-[1.175rem] max-lg:py-12.5 md:max-lg:w-[43.2rem] md:max-lg:h-210.5 md:max-lg:mx-[2.4rem] 2xl:w-350 2xl:h-[46.1875rem] 2xl:mx-65 2xl:py-13.5" data-cid="n192">
                        <div className="w-[64.8rem] h-22.5 block relative max-w-350 mb-7.5 mx-[3.6rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[18.9875rem] max-md:h-[12.5625rem] max-md:max-w-[90%] max-md:mx-[16.9px] md:max-lg:w-[34.5625rem] md:max-lg:h-[7.5625rem] md:max-lg:max-w-270 md:max-lg:mx-[69.1px] 2xl:w-315 2xl:mx-17.5 after:content-[''] after:block after:w-0 after:h-0" data-cid="n193">
                          <div className="w-[489.9px] h-22.5 min-h-px block relative float-left z-2 mr-[3.5625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[18.9875rem] max-md:h-42.5 max-lg:mb-7.5 max-lg:mr-0 md:max-lg:w-[34.5625rem] 2xl:w-[595.3px] 2xl:mr-[69.3px]" data-cid="n194">
                            <div className="h-full block relative text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n195">
                              <div className="h-full block relative" data-cid="n196">
                                <h2 className="h-full block pb-2.5 text-4xl font-bold leading-10" data-cid="n197" data-component="heading">
                                  {"De "}
                                  <span className="inline text-primary" data-cid="n198">
                                    perfecte
                                  </span>
                                  {" balans tussen prijs en kwaliteit."}
                                </h2>
                              </div>
                            </div>
                          </div>
                          <div className="w-[489.9px] min-h-px block relative float-left z-2 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[18.9875rem] md:max-lg:w-[34.5625rem] 2xl:w-[595.3px]" data-cid="n199">
                            <div className="block relative text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n200" />
                          </div>
                        </div>
                        <div className="w-[64.8rem] h-[36.9375rem] block relative max-w-350 mx-[3.6rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[18.9875rem] max-md:max-w-[90%] max-md:mx-[16.9px] md:max-lg:w-[34.5625rem] md:max-lg:max-w-270 md:max-lg:mx-[69.1px] 2xl:w-315 2xl:h-[31.9375rem] 2xl:mx-17.5 after:content-[''] after:block after:w-0 after:h-0" data-cid="n201">
                          <div className="w-full h-[36.9375rem] min-h-px block relative float-left z-2 bg-cover [background-position:50%_50%] bg-no-repeat 2xl:h-[31.9375rem]" data-cid="n202">
                            <div className="h-full block relative overflow-auto text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n203">
                              <div className="block relative" data-cid="n204">
                                <table className="w-full table mb-[0.9375rem] [border-collapse:collapse]" data-cid="n205">
                                  <tbody className="table-row-group align-middle [border-collapse:collapse]" data-cid="n206">
                                    <tr className="table-row align-middle [border-collapse:collapse]" data-cid="n207">
                                      <td className="w-37.5 table-cell min-w-37.5 py-1.5 px-6 align-middle font-bold text-center [border-collapse:collapse] 2xl:w-45" data-cid="n208" />
                                      <td className="w-37.5 table-cell min-w-37.5 py-1.5 px-6 align-middle text-sm font-bold leading-5 text-center [border-collapse:collapse] 2xl:w-45" data-cid="n209">
                                        Prijs
                                      </td>
                                      <td className="w-37.5 table-cell min-w-37.5 py-1.5 px-6 align-middle text-sm font-bold leading-5 text-center [border-collapse:collapse] 2xl:w-45" data-cid="n210">
                                        Snelheid
                                      </td>
                                      <td className="w-37.5 table-cell min-w-37.5 py-1.5 px-6 align-middle text-sm font-bold leading-5 text-center [border-collapse:collapse] 2xl:w-45" data-cid="n211">
                                        Support
                                      </td>
                                      <td className="w-37.5 table-cell min-w-37.5 py-1.5 px-6 align-middle text-sm font-bold leading-5 text-center [border-collapse:collapse] 2xl:w-45" data-cid="n212">
                                        Beheer
                                      </td>
                                      <td className="w-37.5 table-cell min-w-37.5 py-1.5 px-6 align-middle text-sm font-bold leading-5 text-center [border-collapse:collapse] 2xl:w-45" data-cid="n213">
                                        SEO
                                      </td>
                                      <td className="w-37.5 table-cell min-w-37.5 py-1.5 px-6 align-middle text-sm font-bold leading-5 text-center [border-collapse:collapse] 2xl:w-45" data-cid="n214">
                                        AI
                                      </td>
                                    </tr>
                                    <tr className="border-b border-solid border-b-surface-2 table-row align-middle [border-collapse:collapse]" data-cid="n215">
                                      <td className="w-37.5 table-cell min-w-37.5 py-[1.5625rem] px-[0.9375rem] rounded-tl-[15px] rounded-bl-[15px] align-middle font-bold bg-background [border-collapse:collapse] 2xl:w-45" data-cid="n216">
                                        Webtify
                                      </td>
                                      <td className="w-37.5 border-l border-solid border-l-surface-2 table-cell min-w-37.5 py-[1.5625rem] px-[0.9375rem] align-middle text-sm font-normal leading-5 bg-background [border-collapse:collapse] 2xl:w-45" data-cid="n217">
                                        €50 per maand, all-in. Beloofd
                                      </td>
                                      <td className="w-37.5 border-l border-solid border-l-surface-2 table-cell min-w-37.5 py-[1.5625rem] px-[0.9375rem] align-middle text-sm font-normal leading-5 bg-background [border-collapse:collapse] 2xl:w-45" data-cid="n218">
                                        Binnen 4 tot 6 weken live. Vaak nog sneller
                                      </td>
                                      <td className="w-37.5 border-l border-solid border-l-surface-2 table-cell min-w-37.5 py-[1.5625rem] px-[0.9375rem] align-middle text-sm font-normal leading-5 bg-background [border-collapse:collapse] 2xl:w-45" data-cid="n219">
                                        Altijd snel contact via telefoon, whatsapp, mail of chat
                                      </td>
                                      <td className="w-37.5 border-l border-solid border-l-surface-2 table-cell min-w-37.5 py-[1.5625rem] px-[0.9375rem] align-middle text-sm font-normal leading-5 bg-background [border-collapse:collapse] 2xl:w-45" data-cid="n220">
                                        Inbegrepen bij supporturen of zelf aanpassen via het CMS
                                      </td>
                                      <td className="w-37.5 border-l border-solid border-l-surface-2 table-cell min-w-37.5 py-[1.5625rem] px-[0.9375rem] align-middle text-sm font-normal leading-5 bg-background [border-collapse:collapse] 2xl:w-45" data-cid="n221">
                                        Altijd goed vindbaar in Google
                                      </td>
                                      <td className="w-37.5 h-[150.5px] border-l border-solid border-l-surface-2 table-cell min-w-37.5 py-[1.5625rem] px-[0.9375rem] rounded-tr-[15px] rounded-br-[15px] align-middle text-sm font-normal leading-5 bg-background [border-collapse:collapse] 2xl:w-45 2xl:h-[130.5px]" data-cid="n222">
                                        {"Uitbreiden met onze krachtige "}
                                        <a className="inline text-primary cursor-pointer [border-collapse:collapse]" data-cid="n223" data-component="link" href="/ai-agent-fynn">
                                          AI Agent FYNN
                                        </a>
                                      </td>
                                    </tr>
                                    {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} />)}
                                  </tbody>
                                </table>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </article>
            </div>
            <footer className="h-[44.575rem] block overflow-hidden max-md:h-[96.5rem] md:max-lg:h-[59.8125rem] 2xl:h-[45.35rem]" data-cid="n248">
              <div className="h-full block relative z-1 overflow-hidden" data-cid="n249">
                <div className="block relative py-[3.2rem] bg-background bg-cover [background-position:50%_50%] max-lg:py-12.5 2xl:py-13.5" data-cid="n250">
                  <div className="w-288 h-[7.325rem] block relative max-w-350 mx-16 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:max-w-[90%] max-md:mx-[1.175rem] md:max-lg:w-[38.4rem] md:max-lg:h-[4.825rem] md:max-lg:max-w-270 md:max-lg:mx-[4.8rem] 2xl:w-350 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n251">
                    <div className="w-full h-[7.325rem] min-h-px block relative float-left z-2 bg-cover [background-position:50%_50%] bg-no-repeat md:max-lg:h-[4.825rem]" data-cid="n252">
                      <div className="w-[64.8rem] h-full block relative max-w-350 mx-[3.6rem] text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[18.9875rem] max-md:mx-[16.9px] md:max-lg:w-[34.5625rem] md:max-lg:mx-[30.7px] 2xl:w-315 2xl:mx-17.5" data-cid="n253">
                        <div className="h-full block relative" data-cid="n254">
                          <h2 className="block pb-2.5 text-4xl font-bold leading-10" data-cid="n255" data-component="heading">
                            Heel veel
                            <span className="block max-lg:inline after:content-['_'] after:text-foreground after:text-4xl after:font-bold after:leading-10 after:text-left 2xl:after:hidden" data-cid="n256" />
                            <span className="inline text-primary" data-cid="n257">
                              blije
                            </span>
                            {" klanten."}
                          </h2>
                          <p className="block" data-cid="n258">
                            Vertrouwd door 1500+ klanten.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="w-288 block relative max-w-350 mx-16 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:max-w-[90%] max-md:mx-[1.175rem] md:max-lg:w-[38.4rem] md:max-lg:max-w-270 md:max-lg:mx-[4.8rem] 2xl:w-350 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n259">
                    <div className="w-full min-h-px block relative float-left z-2 bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n260">
                      <div className="block relative -mx-2 text-left [overflow-wrap:break-word] bg-clr-4 bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n261">
                        <div className="block relative" data-cid="n262">
                          <div className="block" data-cid="n263" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="block relative z-3000 bg-background bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n264">
                  <div className="w-288 block relative max-w-350 mx-16 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-lg:flex max-md:max-w-[90%] max-md:mx-[1.175rem] max-lg:flex-wrap md:max-lg:w-[38.4rem] md:max-lg:max-w-270 md:max-lg:mx-[4.8rem] 2xl:w-350 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n265">
                    <div className="w-[240.5px] min-h-px block relative float-left z-2 mr-[3.9625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-lg:hidden 2xl:w-[292.3px] 2xl:mr-[4.8125rem]" data-cid="n266" />
                    <div className="w-[240.5px] min-h-px block relative float-left z-2 mr-[3.9625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-lg:hidden 2xl:w-[292.3px] 2xl:mr-[4.8125rem]" data-cid="n267" />
                    <div className="w-[240.5px] min-h-px block relative float-left z-2 mr-[3.9625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-lg:hidden 2xl:w-[292.3px] 2xl:mr-[4.8125rem]" data-cid="n268" />
                    <div className="w-[240.5px] h-[4.3625rem] min-h-px block relative float-left z-2 pt-[1.5625rem] pr-[1.5625rem] pl-[2.1875rem] rounded-tl-[25px] bg-foreground bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] md:max-lg:w-[290.3px] 2xl:w-[292.3px] after:content-['_'] after:block after:absolute after:inset-y-0 after:right-[-1139.5px] after:left-25 after:-z-1 after:h-[4.3625rem] after:text-foreground after:text-base after:font-light after:leading-[1.6875rem] after:bg-foreground after:bg-cover after:[background-position:50%_50%] after:bg-no-repeat max-md:after:right-[-137.5px] md:max-lg:after:right-[-577.7px] 2xl:after:right-[-1727.7px]" data-cid="n269">
                      <div className="w-22.5 block relative max-w-22.5 mr-[90.5px] -mb-7.5 leading-0 text-left bg-cover [background-position:50%_50%] bg-no-repeat max-md:mr-[187.5px] md:max-lg:mr-[140.3px] 2xl:mr-[142.3px]" data-cid="n270">
                        <span className="block relative max-w-full overflow-hidden" data-cid="n271">
                          <img className="w-22.5 h-[4.6875rem] inline relative max-w-full overflow-clip aspect-[auto_462/384]" data-cid="n272" data-component="image" alt="" height="384" src="/assets/cloned/svg/607e2ed608c9.svg" width="462" />
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="block relative z-2000 pt-[1.5625rem] bg-foreground bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n273">
                  <div className="w-288 h-[20.1125rem] block relative max-w-350 mx-16 bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:h-[59.25rem] max-lg:flex max-md:max-w-[90%] max-md:mt-[1.5625rem] max-md:mx-[1.175rem] max-lg:flex-wrap md:max-lg:w-[38.4rem] md:max-lg:h-[34.75rem] md:max-lg:max-w-270 md:max-lg:mx-[4.8rem] 2xl:w-350 2xl:h-[20.5375rem] 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n274">
                    <div className="w-[240.5px] h-49.5 min-h-px block relative float-left z-2 mr-[3.9625rem] py-[1.5625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:mr-0 md:max-lg:w-[290.3px] md:max-lg:mr-[2.1125rem] md:max-lg:mb-7.5 2xl:w-[292.3px] 2xl:mr-[4.8125rem]" data-cid="n275">
                      <div className="block relative text-background text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n276">
                        <div className="block relative" data-cid="n277">
                          <h3 className="block pb-2.5 text-color-003 text-lg font-bold leading-4.5" data-cid="n278" data-component="heading">
                            Websites
                          </h3>
                          <ul className="block pb-4 pl-px leading-6.5 [list-style-type:none] list-outside" data-cid="n279">
                            {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} styles={ListRow2_styles[i]} />)}
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="w-[240.5px] h-49.5 min-h-px block relative float-left z-2 mr-[3.9625rem] py-[1.5625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-lg:mr-0 md:max-lg:w-[290.3px] md:max-lg:mb-7.5 2xl:w-[292.3px] 2xl:mr-[4.8125rem]" data-cid="n288">
                      <div className="block relative text-background text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n289">
                        <div className="block relative" data-cid="n290">
                          <h3 className="block pb-2.5 text-color-003 text-lg font-bold leading-4.5" data-cid="n291" data-component="heading">
                            Webshops
                          </h3>
                          <ul className="block pb-4 pl-px leading-6.5 [list-style-type:none] list-outside" data-cid="n292">
                            {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids2[i]} styles={ListRow2_styles2[i]} />)}
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="w-[240.5px] h-56 min-h-px block relative float-left z-2 mr-[3.9625rem] py-[1.5625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:mr-0 md:max-lg:w-[290.3px] md:max-lg:h-[20.5rem] md:max-lg:mr-[2.1125rem] 2xl:w-[292.3px] 2xl:mr-[4.8125rem]" data-cid="n301">
                      <div className="block relative text-background text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n302">
                        <div className="block relative" data-cid="n303">
                          <h3 className="block pb-2.5 text-color-003 text-lg font-bold leading-4.5" data-cid="n304" data-component="heading">
                            Ontdek Webtify
                          </h3>
                          <ul className="block pb-4 pl-px leading-6.5 [list-style-type:none] list-outside" data-cid="n305">
                            {ListRow2_data3.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids3[i]} styles={ListRow2_styles3[i]} />)}
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="w-[240.5px] h-[20.1125rem] min-h-px block relative float-left z-2 py-[1.5625rem] pr-[1.5625rem] pl-[2.1875rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-lg:h-[20.5rem] max-lg:px-0 md:max-lg:w-[290.3px] 2xl:w-[292.3px] 2xl:h-[20.5375rem]" data-cid="n316">
                      <div className="block relative mb-6 text-background text-left [overflow-wrap:break-word] bg-cover [background-position:50%_50%] bg-no-repeat max-lg:mb-7.5 2xl:mb-[1.9125rem]" data-cid="n317">
                        <div className="block relative" data-cid="n318">
                          <h3 className="block pb-2.5 text-color-003 text-lg font-bold leading-4.5" data-cid="n319" data-component="heading">
                            Contact
                          </h3>
                          <p className="h-[4.4rem] block pb-4" data-cid="n320">
                            Westblaak 130
                            <br className="inline" data-cid="n321" />
                            3012 KM Rotterdam
                          </p>
                          <p className="h-[4.4rem] block pb-4" data-cid="n322">
                            (010) 307 41 33
                            <br className="inline" data-cid="n323" />
                            <a className="inline cursor-pointer" data-cid="n324" data-component="link" href="mailto:support@webtify.nl">
                              support@webtify.nl
                            </a>
                          </p>
                          <p className="block" data-cid="n325">
                            Ma. – Vr. 9.00 – 17.30
                          </p>
                        </div>
                      </div>
                      <ul className="block relative leading-6.5 [list-style-type:none] list-outside bg-cover [background-position:50%_50%] bg-no-repeat after:content-['_'] after:block after:w-full after:h-0 after:text-foreground after:text-[0rem] after:font-light after:leading-6.5" data-cid="n326">
                        <li className="inline-block relative mb-2" data-cid="n327">
                          <a className="box-content h-11 inline-block relative mr-2 rounded-full align-middle text-primary text-center bg-color-004 cursor-pointer before:content-[''] before:block before:relative before:inset-0 before:z-10 before:w-11 before:h-11 before:text-background before:text-[1.375rem] before:leading-11 before:text-center" data-cid="n328" data-component="link" href="https://www.linkedin.com/company/webtify/" target="_blank" title="Volg op LinkedIn">
                            <span className="hidden" data-cid="n329" aria-hidden="true">
                              Volgen
                            </span>
                          </a>
                        </li>
                        <li className="inline-block relative mb-2" data-cid="n330">
                          <a className="box-content h-11 inline-block relative mr-2 rounded-full align-middle text-primary text-center bg-color-004 cursor-pointer before:content-[''] before:block before:relative before:inset-0 before:z-10 before:w-11 before:h-11 before:text-background before:text-[1.375rem] before:leading-11 before:text-center" data-cid="n331" data-component="link" href="https://www.instagram.com/webtify/" target="_blank" title="Volg op Instagram">
                            <span className="hidden" data-cid="n332" aria-hidden="true">
                              Volgen
                            </span>
                          </a>
                        </li>
                        <li className="inline-block relative mb-2" data-cid="n333">
                          <a className="box-content h-11 inline-block relative rounded-full align-middle text-primary text-center bg-color-004 cursor-pointer before:content-[''] before:block before:relative before:inset-0 before:z-10 before:w-11 before:h-11 before:text-background before:text-[1.375rem] before:leading-11 before:text-center" data-cid="n334" data-component="link" href="https://www.tiktok.com/@webtify" target="_blank" title="Volg op TikTok">
                            <span className="hidden" data-cid="n335" aria-hidden="true">
                              Volgen
                            </span>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div className="block relative z-2000 bg-foreground bg-cover [background-position:50%_50%] bg-no-repeat" data-cid="n336">
                  <div className="w-288 h-19 block relative max-w-350 mx-16 pt-2.5 pr-[1.5625rem] bg-cover [background-position:50%_50%] bg-no-repeat max-md:w-[337.5px] max-md:h-64.5 max-md:max-w-[90%] max-md:mx-[1.175rem] md:max-lg:w-[38.4rem] md:max-lg:h-32 md:max-lg:max-w-270 md:max-lg:mx-[4.8rem] 2xl:w-350 2xl:mx-65 after:content-[''] after:block after:w-0 after:h-0" data-cid="n337">
                    <div className="w-full h-16.5 min-h-px block relative float-left z-2 bg-cover [background-position:50%_50%] bg-no-repeat max-md:h-62 md:max-lg:h-29.5" data-cid="n338">
                      <div className="h-full inline-block relative py-5 pr-[2.1875rem] rounded-tr-[25px] text-color-003 text-[0.8125rem] text-left [overflow-wrap:break-word] bg-color-004 bg-cover [background-position:50%_50%] bg-no-repeat before:content-['_'] before:block before:absolute before:inset-y-0 before:right-25 before:-left-[16.8125rem] before:-z-1 before:text-color-003 before:text-[0.8125rem] before:font-light before:leading-[1.6875rem] before:text-left before:bg-color-004 before:bg-cover before:[background-position:50%_50%] before:bg-no-repeat max-md:before:left-[-162.5px] md:max-lg:before:-left-[17.4125rem] 2xl:before:-left-[56.8125rem] after:content-['_'] after:block after:absolute after:inset-y-0 after:right-25 after:-left-[16.8125rem] after:-z-1 after:text-color-003 after:text-[0.8125rem] after:font-light after:leading-[1.6875rem] after:text-left after:bg-color-004 after:bg-cover after:[background-position:50%_50%] after:bg-no-repeat max-md:after:left-[-162.5px] md:max-lg:after:-left-[17.4125rem] 2xl:after:-left-[56.8125rem]" data-cid="n339">
                        <div className="h-full block relative" data-cid="n340">
                          <ul className="h-full block leading-6.5 [list-style-type:none] list-outside" data-cid="n341">
                            <li className="h-6.5 inline-block max-md:h-13 max-md:list-item" data-cid="n342">
                              {"© 2026 "}
                              <a className="inline text-background cursor-pointer" data-cid="n343" data-component="link" href="https://webtify.nl/wp-content/uploads/2026/07/019333193.pdf" rel="noopener" target="_blank">
                                Webtify B.V. is een beschermd merk
                              </a>
                            </li>
                            <li className="h-6.5 inline-block max-md:list-item" data-cid="n344">
                              <a className="inline text-background cursor-pointer" data-cid="n345" data-component="link" href="/algemene-voorwaarden">
                                Algemene voorwaarden
                              </a>
                            </li>
                            <li className="inline-block max-md:list-item" data-cid="n346">
                              <a className="inline text-background cursor-pointer" data-cid="n347" data-component="link" href="https://webtify.nl/service-level-agreement">
                                SLA
                              </a>
                            </li>
                            <li className="inline-block max-md:list-item" data-cid="n348">
                              <a className="inline text-background cursor-pointer" data-cid="n349" data-component="link" href="https://webtify.nl/cookiebeleid/">
                                Cookiebeleid
                              </a>
                            </li>
                            <li className="h-6.5 inline-block max-md:list-item" data-cid="n350">
                              <a className="inline text-background cursor-pointer" data-cid="n351" data-component="link" href="https://webtify.nl/privacy-policy/">
                                Privacy policy
                              </a>
                            </li>
                            <li className="h-6.5 inline-block max-md:list-item" data-cid="n352">
                              <a className="inline text-background cursor-pointer" data-cid="n353" data-component="link" href="/antidiscriminatiebeleid">
                                Antidiscriminatiebeleid
                              </a>
                            </li>
                            <li className="h-6.5 inline-block max-md:list-item" data-cid="n354">
                              <a className="inline text-background cursor-pointer" data-cid="n355" data-component="link" href="https://webtify.nl/klokkenluidersregeling/">
                                Klokkenluidersregeling
                              </a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </div>
      </div>
      {" "}
      <div className="block 2xl:hidden" data-cid="n356">
        <div className="block 2xl:hidden" data-cid="n357" id="wb-wrapper">
          <div className="w-12.5 h-12.5 flex fixed right-2.5 bottom-2.5 z-9998 rounded-[10px] justify-center items-center text-muted-foreground leading-6 bg-accent shadow-[var(--clr-5)_0px_0px_15px_0px] cursor-pointer 2xl:hidden before:content-[''] before:block before:absolute before:inset-0 before:w-12.5 before:h-12.5 before:shadow-[var(--clr-2)_0px_0px_0px_9.13404px] before:rounded-tl-[10px] max-md:before:shadow-[var(--clr-11)_0px_0px_0px_9.73328px] md:max-lg:before:shadow-[var(--clr-12)_0px_0px_0px_7.32297px] 2xl:before:hidden" data-cid="n358" id="wb-widget">
            {" "}
            <div className="w-6 h-6 block leading-4 2xl:hidden" data-cid="n359" id="wb-main-icon">
              <svg className="w-auto h-6 inline overflow-hidden 2xl:hidden" data-cid="n360" data-component="icon" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M3 20l1.3 -3.9c-2.324 -3.437 -1.426 -7.872 2.1 -10.374c3.526 -2.501 8.59 -2.296 11.845 .48c3.255 2.777 3.695 7.266 1.029 10.501c-2.666 3.235 -7.615 4.215 -11.574 2.293l-4.7 1" />
              </svg>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <div className="w-50 h-[9.55rem] block fixed top-[36.075rem] left-267.5 z-9998 invisible opacity-0 max-w-75 rounded-[5px] text-muted-foreground leading-6 transform-[matrix(1,0,0,1,0,10)] max-md:top-[36.825rem] max-md:left-[10.3125rem] md:max-lg:top-[50.075rem] md:max-lg:left-139.5 2xl:hidden" data-cid="n361" id="wb-widget-integrations-list">
            <ul className="h-30 grid justify-end grid-cols-[50px] grid-rows-[60px_60px] [list-style-type:none] list-outside 2xl:hidden" data-cid="n362">
              <li className="w-12.5 h-12.5 grid relative mb-2.5 rounded-[10px] items-center grid-rows-[50px] text-lg leading-[1.625rem] text-center bg-accent cursor-pointer grid-cols-[minmax(0,_1fr)] 2xl:hidden before:content-['Chat_24/7_met_FYNN_AI'] before:block before:absolute before:-inset-y-[0.075rem] before:right-15 before:-left-[10.5625rem] before:z-100 before:w-[8.6875rem] before:h-[1.65rem] before:py-[0.3125rem] before:px-2.5 before:text-foreground before:text-xs before:font-light before:leading-[1.625rem] before:text-center before:bg-accent before:rounded-tl-[5px] 2xl:before:hidden" data-cid="n363">
                <span className="w-6 h-6 block align-middle text-foreground leading-[1.125rem] 2xl:hidden" data-cid="n364">
                  {" "}
                  <svg className="w-6 h-6 inline overflow-hidden 2xl:hidden" data-cid="n365" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M6 4m0 2a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2z" />
                    <path d="M12 2v2" />
                    <path d="M9 12v9" />
                    <path d="M15 12v9" />
                    <path d="M5 16l4 -2" />
                    <path d="M15 14l4 2" />
                    <path d="M9 18h6" />
                    <path d="M10 8v.01" />
                    <path d="M14 8v.01" />
                  </svg>
                  {" "}
                </span>
                {" "}
              </li>
              <li className="w-12.5 h-12.5 grid relative mb-2.5 rounded-[10px] items-center grid-rows-[50px] text-lg leading-[1.625rem] text-center bg-foreground cursor-pointer grid-cols-[minmax(0,_1fr)] 2xl:hidden before:content-['Chat_met_een_medewerker'] before:block before:absolute before:-inset-y-[0.075rem] before:right-15 before:-left-47.5 before:z-100 before:w-40 before:h-[1.65rem] before:py-[0.3125rem] before:px-2.5 before:text-background before:text-xs before:font-light before:leading-[1.625rem] before:text-center before:bg-foreground before:rounded-tl-[5px] 2xl:before:hidden" data-cid="n366">
                <span className="w-6 h-6 block align-middle text-background leading-[1.125rem] 2xl:hidden" data-cid="n367">
                  {" "}
                  <svg className="w-6 h-6 inline overflow-hidden 2xl:hidden" data-cid="n368" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M21 14l-3 -3h-7a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1h9a1 1 0 0 1 1 1v10" />
                    <path d="M14 15v2a1 1 0 0 1 -1 1h-7l-3 3v-10a1 1 0 0 1 1 -1h2" />
                  </svg>
                  {" "}
                </span>
                {" "}
              </li>
            </ul>
            {" "}
            <a className="block py-2 pl-[0.6875rem] text-[0.6875rem] leading-[1.0625rem] text-right cursor-pointer pointer-events-none 2xl:hidden" data-cid="n369" data-component="link" href="https://widgetbird.com/refer/" target="_blank">
              {" Powered by Widgetbird"}
            </a>
            {" "}
          </div>
          {" "}
          <div className="h-[31.9875rem] block fixed right-2.5 bottom-17.5 left-217.5 z-9998 rounded-[5px] text-muted-foreground leading-6 bg-background shadow-[var(--clr-5)_0px_0px_15px_0px] max-md:left-2.5 md:max-lg:left-89.5 2xl:hidden" data-cid="n370" id="wb-widget-integrations-wrapper">
            <div className="block max-h-180 max-md:max-h-183 md:max-lg:max-h-236 2xl:hidden" data-cid="n371">
              <div className="grid pb-5 rounded-tl-[5px] rounded-tr-[5px] text-foreground bg-accent grid-cols-[60px_1fr_60px] grid-rows-1 aspect-[5.556] max-md:aspect-[4.931] 2xl:hidden" data-cid="n372">
                <div className="flex opacity-70 pt-5 pr-2.5 pl-5 justify-center items-center text-xl leading-7.5 text-center cursor-pointer 2xl:hidden" data-cid="n373">
                  <svg className="w-7.5 h-8 block overflow-hidden 2xl:hidden" data-cid="n374" data-component="icon" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M5 12l14 0" />
                    <path d="M5 12l4 4" />
                    <path d="M5 12l4 -4" />
                  </svg>
                  {" "}
                </div>
                {" "}
                <div className="h-13 flex pt-5 justify-center items-center text-center 2xl:hidden" data-cid="n375">
                  {" Chat 24/7 met FYNN AI "}
                </div>
                {" "}
                <div className="flex opacity-70 pt-5 pr-5 pl-2.5 justify-center items-center text-xl leading-7.5 text-center cursor-pointer 2xl:hidden" data-cid="n376">
                  <svg className="w-auto h-6.5 block overflow-hidden 2xl:hidden" data-cid="n377" data-component="icon" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M18 6l-12 12" />
                    <path d="M6 6l12 12" />
                  </svg>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="h-[25.4375rem] block max-w-315 max-h-150 overflow-auto text-center max-md:max-w-[22.1875rem] max-md:max-h-153 md:max-lg:max-w-187 md:max-lg:max-h-206 2xl:hidden" data-cid="n378">
                <div className="w-100 h-100 inline-block relative max-w-full overflow-hidden max-md:w-[22.1875rem] 2xl:hidden" data-cid="n379">
                  <div className="block text-color-002 [font-family:ui-sans-serif,_system-ui,_sans-serif,_'Apple_Color_Emoji',_'Segoe_UI_Emoji',_'Segoe_UI_Symbol',_'Noto_Color_Emoji'] font-normal text-start 2xl:hidden" data-cid="n380">
                    <div className="h-100 flex flex-col bg-background 2xl:hidden" data-cid="n381">
                      <div className="h-[20.0625rem] block py-4 px-6 flex-1 overflow-auto 2xl:hidden" data-cid="n382" id="f0-chat-container">
                        <div className="block 2xl:hidden" data-cid="n383">
                          <div className="border border-solid border-surface block mb-4 p-6 rounded-lg bg-background shadow-[var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-5)_0px_1px_3px_0px,var(--clr-5)_0px_1px_2px_-1px] mx-auto max-w-2xl 2xl:hidden" data-cid="n384">
                            <div className="flex items-start gap-4 2xl:hidden" data-cid="n385">
                              <div className="w-16 h-16 flex rounded-full justify-center items-center shrink-0 overflow-hidden text-background text-2xl font-bold leading-8 shadow-[var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-5)_0px_4px_6px_-1px,var(--clr-5)_0px_2px_4px_-2px] 2xl:hidden" style={{ backgroundImage: "linear-gradient(to right bottom, var(--clr-9) 0%, var(--clr-10) 100%)" }} data-cid="n386">
                                <img className="w-16 h-16 block max-w-full overflow-clip align-middle 2xl:hidden" data-cid="n387" data-component="image" src="/assets/cloned/images/158e78ba34b3.jpg" />
                                {" "}
                              </div>
                              {" "}
                              <div className="block flex-1 2xl:hidden" data-cid="n388">
                                <div className="flex items-center gap-2 2xl:hidden" data-cid="n389">
                                  {" "}
                                </div>
                                {" "}
                                <p className="block mt-2 text-muted text-sm leading-5 2xl:hidden" data-cid="n390">
                                  {" Je praat met FYNN, onze digitale medewerker. Je kan altijd een live chat met een échte Webtify'er starten via de andere chat knop. "}
                                </p>
                                {" "}
                              </div>
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                          <div className="h-15 flex items-start gap-3 2xl:hidden" data-cid="n391">
                            <div className="w-8 h-8 flex rounded-full justify-center items-center shrink-0 overflow-hidden text-sm font-semibold leading-5 bg-foreground 2xl:hidden" data-cid="n392">
                              <img className="w-8 h-8 block max-w-full overflow-clip object-cover align-middle 2xl:hidden" data-cid="n393" data-component="image" src="/assets/cloned/images/158e78ba34b3.jpg" />
                              {" "}
                            </div>
                            {" "}
                            <div className="h-15 block flex-1 2xl:hidden" data-cid="n394">
                              <div className="h-14 inline-block py-2 px-4 rounded-lg text-background bg-foreground shadow-[var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-8)_0px_0px_0px_0px,var(--clr-5)_0px_1px_3px_0px,var(--clr-5)_0px_1px_2px_-1px] max-w-[90%] 2xl:hidden" data-cid="n395">
                                {" "}
                                <p className="block text-sm leading-5 whitespace-pre-wrap 2xl:hidden" data-cid="n396">
                                  Hoi, ik ben FYNN! Waar heb je een vraag over?
                                </p>
                                {" "}
                              </div>
                              {" "}
                              <p className="block mt-1 text-muted text-xs leading-4 2xl:hidden" data-cid="n397" />
                              {" "}
                            </div>
                            {" "}
                          </div>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                      <div className="h-5 flex pb-0.5 w-full 2xl:hidden" data-cid="n398">
                        <button className="h-4.5 flex pb-0.5 px-3 items-center gap-1 text-color-009 text-xs leading-4 text-center cursor-pointer 2xl:hidden" data-cid="n399" data-component="button" type="button">
                          {" Start nieuw gesprek "}
                        </button>
                        {" "}
                      </div>
                      {" "}
                      <div className="border-t border-solid border-t-surface block py-1 px-2 bg-background 2xl:hidden" data-cid="n400">
                        <div className="block relative 2xl:hidden" data-cid="n401">
                          <input className="w-full h-12.5 border border-solid border-color-005 inline-block py-3 pr-12 pl-4 rounded-lg overflow-clip bg-background cursor-text 2xl:hidden" data-cid="n402" data-component="input" placeholder="Type een bericht..." type="text" />
                          {" "}
                          <button className="w-9 h-9 block absolute top-[1.5625rem] right-2 p-2 rounded-lg text-background text-center bg-foreground [translate:0px_-50%] cursor-default 2xl:hidden" data-cid="n403" data-component="button" type="button">
                            <svg className="block overflow-hidden align-middle h-5 w-5 2xl:hidden" data-cid="n404" data-component="icon" viewBox="0 0 576 512" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                              <path d="M290.5 287.7L491.4 86.9 359 456.3 290.5 287.7zM457.4 53L256.6 253.8 88 185.3 457.4 53zM38.1 216.8l205.8 83.6 83.6 205.8c5.3 13.1 18.1 21.7 32.3 21.7 14.7 0 27.8-9.2 32.8-23.1L570.6 8c3.5-9.8 1-20.6-6.3-28s-18.2-9.8-28-6.3L39.4 151.7c-13.9 5-23.1 18.1-23.1 32.8 0 14.2 8.6 27 21.7 32.3z" />
                            </svg>
                            {" "}
                          </button>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <a className="block py-2 px-[0.6875rem] text-[0.6875rem] leading-[1.0625rem] cursor-pointer 2xl:hidden" data-cid="n405" data-component="link" href="https://widgetbird.com/refer/" target="_blank">
              {" Powered by Widgetbird"}
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
      <div className="hidden 2xl:block" data-cid="n406" />
      <div className="hidden 2xl:block" data-cid="n407">
        <div className="hidden 2xl:block" data-cid="n408" id="wb-wrapper">
          <div className="hidden 2xl:w-12.5 2xl:h-12.5 2xl:flex 2xl:fixed 2xl:right-2.5 2xl:bottom-2.5 2xl:z-9998 2xl:rounded-[10px] 2xl:justify-center 2xl:items-center 2xl:text-muted-foreground 2xl:leading-6 2xl:bg-accent 2xl:shadow-[var(--clr-5)_0px_0px_15px_0px] 2xl:cursor-pointer before:content-[''] before:block before:absolute before:inset-0 before:w-12.5 before:h-12.5 before:shadow-[var(--clr-0)_0px_0px_0px_8.22071px] before:rounded-tl-[10px] max-lg:before:hidden" data-cid="n409" id="wb-widget">
            {" "}
            <div className="hidden 2xl:w-6 2xl:h-6 2xl:block 2xl:leading-4" data-cid="n410" id="wb-main-icon">
              <svg className="hidden 2xl:w-6 2xl:h-6 2xl:inline 2xl:overflow-hidden" data-cid="n411" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M3 20l1.3 -3.9c-2.324 -3.437 -1.426 -7.872 2.1 -10.374c3.526 -2.501 8.59 -2.296 11.845 .48c3.255 2.777 3.695 7.266 1.029 10.501c-2.666 3.235 -7.615 4.215 -11.574 2.293l-4.7 1" />
              </svg>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <div className="hidden 2xl:w-50 2xl:h-[9.55rem] 2xl:block 2xl:fixed 2xl:top-[53.575rem] 2xl:left-427.5 2xl:z-9998 2xl:invisible 2xl:opacity-0 2xl:max-w-75 2xl:rounded-[5px] 2xl:text-muted-foreground 2xl:leading-6 2xl:transform-[matrix(1,0,0,1,0,10)]" data-cid="n412" id="wb-widget-integrations-list">
            <ul className="hidden 2xl:h-30 2xl:grid 2xl:justify-end 2xl:grid-cols-[50px] 2xl:grid-rows-[60px_60px] 2xl:[list-style-type:none] 2xl:list-outside" data-cid="n413">
              <li className="hidden 2xl:w-12.5 2xl:h-12.5 2xl:grid 2xl:relative 2xl:mb-2.5 2xl:rounded-[10px] 2xl:items-center 2xl:grid-cols-[50px] 2xl:grid-rows-[50px] 2xl:text-lg 2xl:leading-[1.625rem] 2xl:text-center 2xl:bg-accent 2xl:cursor-pointer before:content-['Chat_24/7_met_FYNN_AI'] before:block before:absolute before:-inset-y-[0.075rem] before:right-15 before:-left-[10.5625rem] before:z-100 before:w-[8.6875rem] before:h-[1.65rem] before:py-[0.3125rem] before:px-2.5 before:text-foreground before:text-xs before:font-light before:leading-[1.625rem] before:text-center before:bg-accent before:rounded-tl-[5px] max-lg:before:hidden" data-cid="n414">
                <span className="hidden 2xl:w-6 2xl:h-6 2xl:block 2xl:align-middle 2xl:text-foreground 2xl:leading-[1.125rem]" data-cid="n415">
                  {" "}
                  <svg className="hidden 2xl:w-6 2xl:h-6 2xl:inline 2xl:overflow-hidden" data-cid="n416" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M6 4m0 2a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2z" />
                    <path d="M12 2v2" />
                    <path d="M9 12v9" />
                    <path d="M15 12v9" />
                    <path d="M5 16l4 -2" />
                    <path d="M15 14l4 2" />
                    <path d="M9 18h6" />
                    <path d="M10 8v.01" />
                    <path d="M14 8v.01" />
                  </svg>
                  {" "}
                </span>
                {" "}
              </li>
              <li className="hidden 2xl:w-12.5 2xl:h-12.5 2xl:grid 2xl:relative 2xl:mb-2.5 2xl:rounded-[10px] 2xl:items-center 2xl:grid-cols-[50px] 2xl:grid-rows-[50px] 2xl:text-lg 2xl:leading-[1.625rem] 2xl:text-center 2xl:bg-foreground 2xl:cursor-pointer before:content-['Chat_met_een_medewerker'] before:block before:absolute before:-inset-y-[0.075rem] before:right-15 before:-left-47.5 before:z-100 before:w-40 before:h-[1.65rem] before:py-[0.3125rem] before:px-2.5 before:text-background before:text-xs before:font-light before:leading-[1.625rem] before:text-center before:bg-foreground before:rounded-tl-[5px] max-lg:before:hidden" data-cid="n417">
                <span className="hidden 2xl:w-6 2xl:h-6 2xl:block 2xl:align-middle 2xl:text-background 2xl:leading-[1.125rem]" data-cid="n418">
                  {" "}
                  <svg className="hidden 2xl:w-6 2xl:h-6 2xl:inline 2xl:overflow-hidden" data-cid="n419" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M21 14l-3 -3h-7a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1h9a1 1 0 0 1 1 1v10" />
                    <path d="M14 15v2a1 1 0 0 1 -1 1h-7l-3 3v-10a1 1 0 0 1 1 -1h2" />
                  </svg>
                  {" "}
                </span>
                {" "}
              </li>
            </ul>
            {" "}
            <a className="hidden 2xl:block 2xl:py-2 2xl:pl-[0.6875rem] 2xl:text-[0.6875rem] 2xl:leading-[1.0625rem] 2xl:text-right 2xl:cursor-pointer 2xl:pointer-events-none" data-cid="n420" href="https://widgetbird.com/refer/" target="_blank">
              {" Powered by Widgetbird"}
            </a>
            {" "}
          </div>
          {" "}
          <div className="hidden 2xl:w-100 2xl:h-[39.6125rem] 2xl:block 2xl:fixed 2xl:top-[23.5125rem] 2xl:left-377.5 2xl:z-9998 2xl:invisible 2xl:opacity-0 2xl:rounded-[5px] 2xl:text-muted-foreground 2xl:leading-6 2xl:bg-background 2xl:shadow-[var(--clr-5)_0px_0px_15px_0px] 2xl:transform-[matrix(1,0,0,1,0,10)]" data-cid="n421" id="wb-widget-integrations-wrapper">
            <div className="hidden 2xl:h-[29.9375rem] 2xl:block 2xl:max-h-250" data-cid="n422">
              <div className="hidden 2xl:h-18 2xl:grid 2xl:pb-5 2xl:rounded-tl-[5px] 2xl:rounded-tr-[5px] 2xl:grid-cols-[60px_280px_60px] 2xl:grid-rows-[52px] 2xl:text-foreground 2xl:bg-accent" data-cid="n423">
                <div className="hidden 2xl:h-13 2xl:flex 2xl:opacity-70 2xl:pt-5 2xl:pr-2.5 2xl:pl-5 2xl:justify-center 2xl:items-center 2xl:text-xl 2xl:leading-7.5 2xl:text-center 2xl:cursor-pointer" data-cid="n424">
                  <svg className="hidden 2xl:w-7.5 2xl:h-8 2xl:block 2xl:overflow-hidden" data-cid="n425" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M5 12l14 0" />
                    <path d="M5 12l4 4" />
                    <path d="M5 12l4 -4" />
                  </svg>
                  {" "}
                </div>
                {" "}
                <div className="hidden 2xl:h-13 2xl:flex 2xl:pt-5 2xl:justify-center 2xl:items-center 2xl:text-center" data-cid="n426">
                  {" Chat 24/7 met FYNN AI "}
                </div>
                {" "}
                <div className="hidden 2xl:h-13 2xl:flex 2xl:opacity-70 2xl:pt-5 2xl:pr-5 2xl:pl-2.5 2xl:justify-center 2xl:items-center 2xl:text-xl 2xl:leading-7.5 2xl:text-center 2xl:cursor-pointer" data-cid="n427">
                  <svg className="hidden 2xl:w-6.5 2xl:h-6.5 2xl:block 2xl:overflow-hidden" data-cid="n428" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M18 6l-12 12" />
                    <path d="M6 6l12 12" />
                  </svg>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="hidden 2xl:w-100 2xl:h-[25.4375rem] 2xl:block 2xl:max-w-475 2xl:max-h-220 2xl:overflow-auto 2xl:text-center" data-cid="n429">
                <iframe className="hidden 2xl:w-100 2xl:h-100 2xl:inline 2xl:max-w-full 2xl:overflow-clip" data-cid="n430" height="400px" width="100%" />
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="hidden 2xl:h-30.5 2xl:block 2xl:max-h-250" data-cid="n431">
              <div className="hidden 2xl:h-18 2xl:grid 2xl:pb-5 2xl:rounded-tl-[5px] 2xl:rounded-tr-[5px] 2xl:grid-cols-[60px_280px_60px] 2xl:grid-rows-[52px] 2xl:text-background 2xl:bg-foreground" data-cid="n432">
                <div className="hidden 2xl:h-13 2xl:flex 2xl:opacity-70 2xl:pt-5 2xl:pr-2.5 2xl:pl-5 2xl:justify-center 2xl:items-center 2xl:text-xl 2xl:leading-7.5 2xl:text-center 2xl:cursor-pointer" data-cid="n433">
                  <svg className="hidden 2xl:w-7.5 2xl:h-8 2xl:block 2xl:overflow-hidden" data-cid="n434" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M5 12l14 0" />
                    <path d="M5 12l4 4" />
                    <path d="M5 12l4 -4" />
                  </svg>
                  {" "}
                </div>
                {" "}
                <div className="hidden 2xl:h-13 2xl:flex 2xl:pt-5 2xl:justify-center 2xl:items-center 2xl:text-center" data-cid="n435">
                  {" Chat met een medewerker "}
                </div>
                {" "}
                <div className="hidden 2xl:h-13 2xl:flex 2xl:opacity-70 2xl:pt-5 2xl:pr-5 2xl:pl-2.5 2xl:justify-center 2xl:items-center 2xl:text-xl 2xl:leading-7.5 2xl:text-center 2xl:cursor-pointer" data-cid="n436">
                  <svg className="hidden 2xl:w-6.5 2xl:h-6.5 2xl:block 2xl:overflow-hidden" data-cid="n437" fill="none" height="24" stroke="currentColor" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M18 6l-12 12" />
                    <path d="M6 6l12 12" />
                  </svg>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="hidden 2xl:w-75 2xl:h-12.5 2xl:block 2xl:max-w-475 2xl:max-h-220 2xl:p-[1.5625rem] 2xl:overflow-auto 2xl:text-center" data-cid="n438" />
              {" "}
            </div>
            {" "}
            <a className="hidden 2xl:block 2xl:py-2 2xl:px-[0.6875rem] 2xl:text-[0.6875rem] 2xl:leading-[1.0625rem] 2xl:cursor-pointer 2xl:pointer-events-none" data-cid="n439" href="https://widgetbird.com/refer/" target="_blank">
              {" Powered by Widgetbird"}
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </div>
      <div className="h-full flex fixed top-0 inset-x-0 z-9000000 p-4 justify-center items-center bg-color-007 [pointer-events:all] max-md:items-end max-md:p-0" data-cid="n440">
        <div className="h-[23.3125rem] block max-w-180 p-5 rounded-[5px] bg-background shadow-[var(--clr-7)_0px_0px_64px_0px] [pointer-events:all] max-md:h-[28.9875rem] max-md:max-w-[23.4375rem] max-md:max-h-199 max-md:pt-2 max-md:pb-4 max-md:px-2 max-md:overflow-auto max-md:shadow-[var(--color-007)_0px_0px_64px_0px] max-md:rounded-br-[initial] max-md:rounded-bl-[initial]" data-cid="n441" aria-describedby="ConsentStudioConsentModalDescription" aria-labelledby="ConsentStudioConsentModalTitle" aria-modal="true" lang="nl" role="dialog">
          <div className="h-full block text-color-001 leading-6 [pointer-events:all]" data-cid="n442">
            <div className="flex justify-between items-center font-medium [pointer-events:all] max-md:mb-2" data-cid="n443">
              <div className="w-full flex max-w-[90%] items-center gap-4 [pointer-events:all]" data-cid="n444" id="ConsentStudioConsentModalTitle">
                <strong className="box-content block font-bold [pointer-events:all]" data-cid="n445">
                  Onze website gebruikt cookies
                </strong>
                {" "}
              </div>
              {" "}
              <div className="flex items-stretch shrink-0 gap-2 [pointer-events:all] max-md:shrink-[initial]" data-cid="n446">
                <button className="h-9.5 flex py-[0.4375rem] px-3.5 rounded-[3px] items-center justify-items-center text-color-002 text-[0.875rem] text-center bg-surface-4 cursor-pointer [pointer-events:all]" data-cid="n447" data-component="button" aria-label="Overzicht" type="button">
                  <svg className="w-auto h-4.5 block relative max-w-[17.5px] max-h-[17.5px] mr-0.5 overflow-hidden leading-[1.3125rem] [pointer-events:all]" data-cid="n448" data-component="icon" aria-hidden="true" fill="currentColor" height="32" viewBox="0 0 256 256" width="32" xmlns="http://www.w3.org/2000/svg">
                    <path d="M164.49,163.51a12,12,0,1,1-17,0A12,12,0,0,1,164.49,163.51Zm-81-8a12,12,0,1,0,17,0A12,12,0,0,0,83.51,155.51Zm9-39a12,12,0,1,0-17,0A12,12,0,0,0,92.49,116.49Zm48-1a12,12,0,1,0,0,17A12,12,0,0,0,140.49,115.51ZM232,128A104,104,0,1,1,128,24a8,8,0,0,1,8,8,40,40,0,0,0,40,40,8,8,0,0,1,8,8,40,40,0,0,0,40,40A8,8,0,0,1,232,128Zm-16.31,7.39A56.13,56.13,0,0,1,168.5,87.5a56.13,56.13,0,0,1-47.89-47.19,88,88,0,1,0,95.08,95.08Z" />
                  </svg>
                  {" Overzicht "}
                </button>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="h-[9.1875rem] block [pointer-events:all] max-md:h-[7.7375rem]" data-cid="n449">
              <div className="h-full block [pointer-events:all] max-md:box-content max-md:border-t max-md:border-solid max-md:border-t-border max-md:border-b max-md:border-b-border max-md:relative max-md:max-h-[7.6125rem] max-md:overflow-x-auto max-md:overflow-y-scroll" data-cid="n450" id="ConsentStudioConsentModalDescription">
                <div className="block mt-4 mb-2 [pointer-events:all] max-md:pt-2 max-md:mt-0" data-cid="n451">
                  <p className="block mb-3.5 text-sm leading-[1.3125rem] [pointer-events:all] max-md:mb-0" data-cid="n452">
                    {"Om uw voorkeuren te onthouden (“Functioneel”), om het verkeer naar onze site te meten (“Analytics”), en om inhoud en advertenties te personaliseren en sociale media-functies mogelijk te maken (“Marketing & Sociale Media”), gebruiken we cookies en vergelijkbare technologieën. We delen ook informatie over uw gebruik van onze website met onze sociale media-, analytics- en advertentiepartners, die deze kunnen combineren met andere informatie die ze hebben verzameld van uw gebruik van hun diensten. U kunt uw toestemming op elk moment wijzigen of intrekken."}
                  </p>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="block mt-4 mb-2 [pointer-events:all]" data-cid="n453" />
              {" "}
            </div>
            {" "}
            <div className="block mt-6 [pointer-events:all]" data-cid="n454">
              <ul className="flex mt-4 mb-6 flex-wrap gap-y-2 [list-style-type:none] list-outside [pointer-events:all] max-md:flex-col max-md:items-start" data-cid="n455">
                {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
              </ul>
              {" "}
              <div className="flex gap-2 grid-cols-[1fr_1fr] [pointer-events:all] max-md:flex-col max-md:grid-cols-[initial]" data-cid="n468">
                {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} styles={Tile2_styles[i]} />)}
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </div>
      <div className="w-px h-px block absolute top-[149.8125rem] left-0 -m-px overflow-hidden whitespace-nowrap text-nowrap" data-cid="n472" aria-atomic="true" aria-live="polite" id="cs-announcer">
        Toestemmingsvenster geopend
      </div>
      <div className="block 2xl:hidden" data-cid="n473" />
    </>
  );
}
